---
- hosts: localhost
  connection: local
  vars:
     vnode_prefix: vnode-
  roles:
  - name: Set cri runtime to containerd in Ubuntu 22.04
    set_fact:
      kube_cri_runtime: "containerd"
    when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 22
  - role: grycap.nfs
    nfs_mode: 'wn'
  - role: 'grycap.kubernetes'
    kube_type_of_node: 'wn'
    kube_server: '{{kube_front_end_ip}}'
    kube_api_server: '{{ kube_front_end_ip }}'
    kube_nvidia_driver_version: "465"
