---
- hosts: localhost
  connection: local
  vars:
     vnode_prefix: vnode-
     export_hosts: "*.localdomain"
     export_line: "(fsid=0,rw,async,no_root_squash,no_subtree_check,insecure)"

  pre_tasks:
  - name: Create dir for the NFS PV
    file: path=/pv state=directory mode=755
  - name: Create auth file dir
    file: path=/etc/kubernetes/pki state=directory mode=755 recurse=yes
  - name: Create auth data file with an admin user
    copy: content='{{kube_admin_token}},{{kube_admin_username}},100,"users,system:masters"' dest=/etc/kubernetes/pki/auth mode=600
  - name: Do not use fsid=0 in Ubuntu 22.04 and set cri runtime to containerd
    set_fact:
      export_line: "(rw,async,no_root_squash,no_subtree_check,insecure)"
      kube_cri_runtime: "containerd"
    when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 22
  - name: Do not use *.localdomain in EC2
    set_fact:
      export_hosts: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
    when: IM_NODE_CLOUD_TYPE is defined and IM_NODE_CLOUD_TYPE == 'EC2'

  roles:
  - role: grycap.nfs
    nfs_mode: 'front'
    nfs_exports: [{path: "/pv", export: '{{ export_hosts }}{{ export_line }}'}]
  - role: grycap.kubernetes
    kube_server: '{{ kube_front_end_ip }}'
    kube_api_server: '{{ kube_front_end_ip }}'
    kube_apiserver_options:
      - {option: "--service-node-port-range", value: "80-35000"}
      - {option: "--token-auth-file", value: "/etc/kubernetes/pki/auth"}
    kube_deploy_dashboard: true
    kube_install_metrics: true
    kube_cert_public_ip: "{{ IM_NODE_PUBLIC_IP }}"
    kube_install_helm_version: "v3.8.2"

  tasks:
  - slurp: src=/etc/kubernetes/admin.conf
    register: slurpfile
    name: Read kubeconfig file
    ignore_errors: true
  - debug: msg="{{ slurpfile['content'] | b64decode | replace(IM_NODE_PRIVATE_IP, IM_NODE_PUBLIC_IP ) }}"
    ignore_errors: true
    name: kube_conf
