---
- hosts: localhost
  connection: local
  roles:
  - role: grycap.nfs
    nfs_mode: 'client'
    nfs_client_imports: [{ local: "/home", remote: "/home", server_host: "{{ slurm_front_end_ip }}" }]
  - role: grycap.slurm
    slurm_type_of_node: 'wn'
    slurm_server_ip: '{{ slurm_front_end_ip }}'