---
- hosts: localhost
  connection: local
  vars:
    poll_time: 5
    max_time: "{{ max_download_time | default(1800) }}"
    pvc_name: "{{ k8s_pvc_name | default('') }}"
    pvc_namespace: "{{ k8s_pvc_namespace | default('') }}"
  tasks:
  - name: Download data to a local path
    block:

    - name: Create "{{ local_path }}" if needed
      file: 
        path: "{{ local_path }}"
        state: directory
        recurse: yes

    - set_fact:
        poll_time: 0
      when: wait_to_download | bool

    - name: Download "{{ data_url }}"
      get_url: 
        url: "{{ data_url }}"
        dest: "{{ local_path }}"
      async: "{{ max_time }}"
      poll: "{{ poll_time }}"

    when: pvc_name == '' or pvc_namespace == ''

  - name: Download data to a K8s PVC
    block:

    - name: Gen URL hash
      set_fact:
        url_hash: "{{ data_url | hash('sha256') }}"

    - name: Create job file
      copy:
        contents: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            namespace: {{ pvc_namespace }}
            name: pv-load-{{ url_hash }}
          spec:
            template:
              spec:
                volumes:
                  - name: pv-storage
                    persistentVolumeClaim:
                      claimName: {{ pvc_name }}
                containers:
                  - name: pv-load
                    image: alpine
                    command:
                    - sh
                    - -c
                    - wget -P /data '{{ data_url }}'
                    volumeMounts:
                      - mountPath: '/data'
                        name: pv-storage
        dest: "/opt/wget_job_{{ url_hash }}.yaml"

    - name: Create wget job
      command: kubectl apply -f /opt/wget_job_{{ url_hash }}.yaml
      environment:
        KUBECONFIG: "{{KUBECONFIG}}"

    when: pvc_name != '' and pvc_namespace != ''
